### ISSUE TITLE
Add Filter Support

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-twig#2]
https://github.com/justjohn/twig.js/wiki/Extending-twig.js#filters

**Comment by thiagodemellobueno** [comment]
https://github.com/kalamuna/kalastatic/issues/340

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic-twig-filters

**Comment by RobLoach** [comment]
`options.filters` is now expanded. We should do the same for `options.functions` and others.
